namespace DocReader.UnitTests;

/// <summary>
/// Access to the synthetic samples copied next to the test binaries. They are generated by
/// <c>scripts/make-samples.mjs</c>, so a fixture is never a committed binary blob.
/// </summary>
public static class Samples
{
    public const string OnePagePdf = "comprovante-1-pagina.pdf";
    public const string ThreePagePdf = "contrato-3-paginas.pdf";
    public const string SixtyPagePdf = "dossie-60-paginas.pdf";
    public const string Png = "documento-digitalizado.png";
    public const string TwoPageTiff = "documento-frente-verso.tif";
    public const string DisguisedExecutable = "executavel-disfarcado.pdf";
    public const string CorruptedPdf = "pdf-corrompido.pdf";

    public static string PathOf(string fileName) =>
        Path.Combine(AppContext.BaseDirectory, "samples", fileName);

    public static byte[] BytesOf(string fileName) => File.ReadAllBytes(PathOf(fileName));

    public static MemoryStream StreamOf(string fileName) => new(BytesOf(fileName), writable: false);
}
