// <auto-generated />
using System;
using DocReader.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DocReader.Infrastructure.Migrations
{
    [DbContext(typeof(DocReaderDbContext))]
    [Migration("20260925225201_AddRetentionPolicies")]
    partial class AddRetentionPolicies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocReader.Domain.Catalog.ProductService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_product_services_code");

                    b.ToTable("product_services", (string)null);
                });

            modelBuilder.Entity("DocReader.Domain.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ClassificationConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("classification_confidence");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("DetectedDocumentType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("detected_document_type");

                    b.Property<string>("ExpectedDocumentType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("expected_document_type");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_reference");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("last_error_message");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_file_name");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<Guid?>("ProductServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_service_id");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("protocol");

                    b.Property<DateTimeOffset?>("PurgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purged_at");

                    b.Property<int?>("RetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("retention_days");

                    b.Property<Guid?>("RetentionPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("retention_policy_id");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<string>("UploadChannel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("upload_channel");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("DetectedDocumentType")
                        .HasDatabaseName("ix_documents_detected_document_type");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_documents_expires_at_pending")
                        .HasFilter("status <> 'PURGED' AND expires_at IS NOT NULL");

                    b.HasIndex("ProductServiceId")
                        .HasDatabaseName("ix_documents_product_service_id");

                    b.HasIndex("Protocol")
                        .IsUnique()
                        .HasDatabaseName("ix_documents_protocol");

                    b.HasIndex("RetentionPolicyId");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_documents_sha256");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_documents_status");

                    b.HasIndex("UploadChannel")
                        .HasDatabaseName("ix_documents_upload_channel");

                    b.HasIndex("UploadedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_documents_uploaded_at");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("DocReader.Domain.Documents.DocumentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Details")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("details");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("stage");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "OccurredAt")
                        .HasDatabaseName("ix_document_events_document_id_occurred_at");

                    b.ToTable("document_events", (string)null);
                });

            modelBuilder.Entity("DocReader.Domain.Extractions.DocumentExtraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClassifierVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classifier_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("ExtractorVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("extractor_version");

                    b.Property<string>("OcrModelVersion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ocr_model_version");

                    b.Property<string>("OcrProvider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ocr_provider");

                    b.Property<decimal?>("OverallConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("overall_confidence");

                    b.Property<string>("PageTextsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("page_texts");

                    b.Property<Guid>("ProcessingJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("processing_job_id");

                    b.Property<string>("RawOcrResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_ocr_result");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<int?>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("StructuredResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("structured_result");

                    b.HasKey("Id");

                    b.HasIndex("ProcessingJobId")
                        .HasDatabaseName("ix_extractions_processing_job_id");

                    b.HasIndex("DocumentId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_extractions_document_id_created_at");

                    b.ToTable("extractions", (string)null);
                });

            modelBuilder.Entity("DocReader.Domain.Extractions.ExtractedField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BoundingBoxJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("bounding_box");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<Guid>("ExtractionId")
                        .HasColumnType("uuid")
                        .HasColumnName("extraction_id");

                    b.Property<string>("FieldPath")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("field_path");

                    b.Property<string>("NormalizedValue")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("normalized_value");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<string>("RawValue")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("raw_value");

                    b.Property<string>("ValidationMessagesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_messages");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("validation_status");

                    b.HasKey("Id");

                    b.HasIndex("ExtractionId", "FieldPath")
                        .IsUnique()
                        .HasDatabaseName("ix_extracted_fields_extraction_id_field_path");

                    b.ToTable("extracted_fields", (string)null);
                });

            modelBuilder.Entity("DocReader.Domain.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FileSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_sha256");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.HasKey("Key");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_keys_expires_at");

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("DocReader.Domain.Processing.ProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("locked_by");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<int>("PagesCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("pages_completed");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("stage");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique()
                        .HasDatabaseName("ux_processing_jobs_document_id_active")
                        .HasFilter("status IN ('PENDING', 'RUNNING')");

                    b.HasIndex("Status", "AvailableAt", "CreatedAt")
                        .HasDatabaseName("ix_processing_jobs_status_available_at_created_at");

                    b.ToTable("processing_jobs", (string)null);
                });

            modelBuilder.Entity("DocReader.Domain.Retention.RetentionPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_type");

                    b.Property<Guid?>("ProductServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_service_id");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("retention_days");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProductServiceId");

                    b.HasIndex("DocumentType", "ProductServiceId")
                        .IsUnique()
                        .HasDatabaseName("ux_retention_policies_scope");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("DocumentType", "ProductServiceId"), false);

                    b.ToTable("retention_policies", null, t =>
                        {
                            t.HasCheckConstraint("ck_retention_policies_days", "retention_days >= 1 AND retention_days <= 36500");
                        });
                });

            modelBuilder.Entity("DocReader.Infrastructure.Persistence.ProtocolSequence", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<long>("LastNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_number");

                    b.HasKey("Day");

                    b.ToTable("protocol_sequences", (string)null);
                });

            modelBuilder.Entity("DocReader.Domain.Documents.Document", b =>
                {
                    b.HasOne("DocReader.Domain.Catalog.ProductService", "ProductService")
                        .WithMany()
                        .HasForeignKey("ProductServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DocReader.Domain.Retention.RetentionPolicy", "RetentionPolicy")
                        .WithMany()
                        .HasForeignKey("RetentionPolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProductService");

                    b.Navigation("RetentionPolicy");
                });

            modelBuilder.Entity("DocReader.Domain.Documents.DocumentEvent", b =>
                {
                    b.HasOne("DocReader.Domain.Documents.Document", null)
                        .WithMany("Events")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocReader.Domain.Extractions.DocumentExtraction", b =>
                {
                    b.HasOne("DocReader.Domain.Documents.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocReader.Domain.Processing.ProcessingJob", null)
                        .WithMany()
                        .HasForeignKey("ProcessingJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocReader.Domain.Extractions.ExtractedField", b =>
                {
                    b.HasOne("DocReader.Domain.Extractions.DocumentExtraction", null)
                        .WithMany("Fields")
                        .HasForeignKey("ExtractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocReader.Domain.Idempotency.IdempotencyRecord", b =>
                {
                    b.HasOne("DocReader.Domain.Documents.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocReader.Domain.Processing.ProcessingJob", b =>
                {
                    b.HasOne("DocReader.Domain.Documents.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocReader.Domain.Retention.RetentionPolicy", b =>
                {
                    b.HasOne("DocReader.Domain.Catalog.ProductService", "ProductService")
                        .WithMany()
                        .HasForeignKey("ProductServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProductService");
                });

            modelBuilder.Entity("DocReader.Domain.Documents.Document", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("DocReader.Domain.Extractions.DocumentExtraction", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
